package employeerostering.employeerostering;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleAgendaListner implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RuleAgendaListner() {
    }




}