package rulebased.employeerostering;

import employeerostering.employeerostering.Shift;
import employeerostering.employeerostering.DayOffRequest;
import employeerostering.employeerostering.ShiftAssignment;
import employeerostering.employeerostering.Employee;
import employeerostering.employeerostering.Skill;
import java.util.List;

query "AssignedShifts"
    assigned : List() from collect ( ShiftAssignment( employee != null ) )
end

query "unAssignedShifts"
    unAssigned : List() from collect ( ShiftAssignment( employee == null ) )
end